pipeline {
    agent any
    
    tools {
        nodejs 'nodejs23'
    }
    
    environment {
        SCANNER_HOME = tool 'sonar-scanner'
        TERRAFORM_HOME = tool 'terraform' 
        
        BUILD_NUMBER = "${env.BUILD_NUMBER ?: 'latest'}"
        TF_DIR       = 'terraform'
        PATH         = "${env.TERRAFORM_HOME}:${env.PATH}" 
    }

    stages {
        stage('SCM Checkout') {
            steps {
                git branch: 'local-dev', changelog: false, poll: false, url: 'https://github.com/andrewferdinandus/3-Tier-DevSecOps-Project.git'
            }
        }
        
        stage('Frontend Compilation') {
            steps {
                dir('client') {
                    sh 'find . -name "*.js" -exec node --check {} +'
                }
            }
        }
        
        stage('Backend Compilation') {
            steps {
                dir('api') {
                    sh 'find . -name "*.js" -exec node --check {} +'
                }
            }
        }
        
        stage('Gitleaks Scan') {
            steps {
                sh 'gitleaks detect --source ./client --exit-code 1'
                sh 'gitleaks detect --source ./api --exit-code 1'
            }
        }
        
        stage('Sonarqube Analysis') {
            steps {
                withSonarQubeEnv('sonar-server') {
                    sh "${SCANNER_HOME}/bin/sonar-scanner -Dsonar.projectName=NodeJS-Project -Dsonar.projectKey=NodeJS-Project"
                }
            }
        }
        
        stage('Quality Gate Check') {
            steps {
                timeout(time: 10, unit: 'MINUTES') { 
                    waitForQualityGate abortPipeline: true 
                }
            }
        }
        
        stage('Trivy FS Scan') {
            steps {
                sh 'trivy fs --format table -o trivy-fs-report.html .'
            }
        }
        
        stage('Docker build and Push Backend') {
            steps {
                script {
                    def imageName = "andrewferdi/backend-latest"
                    def buildTag = "${imageName}:${env.BUILD_NUMBER}"
                    def latestTag = "${imageName}:latest"
                    
                    withDockerRegistry(credentialsId: 'docker-creds') {
                        dir('api') {
                            sh "docker build -t ${buildTag} -t ${latestTag} ."
                            sh "trivy image --format table -o backend-image-report.html ${buildTag}"
                            sh "docker push ${buildTag}"
                            sh "docker push ${latestTag}"
                        }
                    }
                }
            }
        }

        stage('Docker build and Push Frontend') {
            steps {
                script {
                    def imageName = "andrewferdi/frontend-latest"
                    def buildTag = "${imageName}:${env.BUILD_NUMBER}"
                    def latestTag = "${imageName}:latest"
                    
                    withDockerRegistry(credentialsId: 'docker-creds') {
                        dir('client') {
                            sh "docker build -t ${buildTag} -t ${latestTag} ."
                            sh "trivy image --format table -o frontend-image-report.html ${buildTag}"
                            sh "docker push ${buildTag}"
                            sh "docker push ${latestTag}"
                        }
                    }
                }
            }
        }
        
        stage('EKS Provisioning') {
            steps {
                dir("${TF_DIR}") {
                    script {
                        withCredentials([[
                            $class: 'AmazonWebServicesCredentialsBinding', 
                            credentialsId: 'aws-creds', 
                            accessKeyVariable: 'AWS_ACCESS_KEY_ID', 
                            secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                        ]]) {
                            // No need for full paths now!
                            sh 'terraform init'
                            sh 'terraform apply -auto-approve'
                        }
                    }
                }
            }
        }
    }
}