# --- BACKEND ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: andrewferdi/backend-latest:IMAGE_TAG
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 5000
  selector:
    app: backend

# --- FRONTEND ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: andrewferdi/frontend-latest:IMAGE_TAG
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer # Tells AWS to provision an Elastic Load Balancer (ELB)
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend
